name: Android E2E

on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - uses: android-actions/setup-android@v3

      - name: Install Node deps
        run: npm ci

      - name: Run E2E on emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        env:
          ANDROID_APP_PATH: ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk
        with:
          api-level: 33
          arch: x86_64
          profile: pixel_6
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: |
            set -e
            ./gradlew assembleDebug --stacktrace
            adb wait-for-device
            for i in $(seq 1 90); do [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" = "1" ] && break; sleep 1; done
            adb shell input keyevent 82 || true

            # uia2 driver kurulu değilse kur; varsa güncelle, hata vermesin
            npx appium driver install uiautomator2 || npx appium driver update uiautomator2 || true

            # Appium'ı WDIO başlatır → direkt test
            npx wdio run ./wdio.android.conf.js
