# path: .github/workflows/android-e2e.yml
name: Android E2E

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Node deps
        run: npm ci

      - name: Run E2E on emulator (stabil)
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          profile: pixel_6
          disable-animations: true
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          script: |
            ./gradlew assembleDebug --stacktrace
            export ANDROID_APP_PATH=$PWD/app/build/outputs/apk/debug/app-debug.apk
            npx appium driver install uiautomator2
            # Appium server'ı başlat
            npx appium --log-level warn > appium.log 2>&1 &
            # 4723 portu hazır olana kadar bekle (30 sn'ye kadar)
            for i in {1..30}; do (echo > /dev/tcp/127.0.0.1/4723) >/dev/null 2>&1 && break; sleep 1; done
            npx wdio run ./wdio.android.conf.js

      - name: Upload artifacts (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: |
            app/build/outputs/apk/debug/*.apk
            appium.log
